"indention options"
filetype indent on 		    "enable indentation filetype spec"
set autoindent			    "autoindent files"
set expandtab			    "changes tab to spaces"
set tabstop=4			    "4 spaces=1 tab"
set softtabstop=4		    "delete 4 spaces"
set shiftwidth=4		    "use 4 spaces when shift"

"search options"
set hlsearch 			    "search highlight"
set ignorecase			    "ignore case in search"
set incsearch			    "show partial matches"

"text options"
set display+=lastline		"try to show paragraph's last line"
set encoding=utf-8		    "supports unicode"
set linebreak			    "avoid wrapping line in a middle of a word"
syntax enable			    "enable syntax highlight"


"UI"
set ruler			        "show the cursor position"
set wildmenu			    "show options"
colorscheme badwolf         "changes the colors scheme"
set colorcolumn=80          "set a column to not go over >:("
set number			        "show the line number"
set visualbell		        "disable that fricking bell on errors"
set mouse=a			        "enable mouse for scrolling and resizing"
set title			        "show the title of the file being edited"

"misc"
set dir=~/.cache/vim		"directory for backup files"
set confirm			        "confirmation when closing unsaved file"
set history=1000		    "Increase undo limit"
set spell			        "spell checking"
